<link rel="stylesheet" href="../../css/bootstrap.min.css"> 
<link rel="stylesheet" href="../../css/bootstrap-select.min.css"> 
<link rel="stylesheet" href="../../css/all.min.css">
<link rel="stylesheet" href="../../css/fontawesome.min.css"> 
<link rel="stylesheet" href="../assets/css/main.css">
<link rel="sylesheet" href="../assets/css/style.css">
<link rel="stylesheet" href="../assets/css/forms.css">
<link rel="stylesheet" href="../../datatables/datatables.min.css">
<link rel="stylesheet" href="../../datatables/Buttons-1.5.4/css/buttons.dataTables.min.css">